INSERT INTO USER (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (0, 0, 'aaa', 'alma@alma.hu', 'alma', 'ADMIN'); 
INSERT INTO USER (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (1, 0, 'kkk', 'korte@korte.com', 'korte', 'USER');

INSERT INTO DIRECTOR (ID, VERSION, DIRECTOR_NAME, NATIONALITY, BIO) VALUES (1, 0, 'Ruben Fleischer', 'USA', 'a');
INSERT INTO DIRECTOR (ID, VERSION, DIRECTOR_NAME, NATIONALITY, BIO) VALUES (2, 0, 'Damien Chazelle', 'USA', 'b');
INSERT INTO DIRECTOR (ID, VERSION, DIRECTOR_NAME, NATIONALITY, BIO) VALUES (3, 0, 'Brad Bird', 'USA', 'c');
INSERT INTO DIRECTOR (ID, VERSION, DIRECTOR_NAME, NATIONALITY, BIO) VALUES (4, 0, 'Corin Hardy', 'USA', 'd');

INSERT INTO MOVIE (ID, VERSION, TITLE, GENRE, PUBLICATION_DATE, DIRECTOR_ID) VALUES (1, 0, 'AZ ELSO EMBER', 'eletrajzi drama', '2018-09-01', 1);
INSERT INTO MOVIE (ID, VERSION, TITLE, GENRE, PUBLICATION_DATE, DIRECTOR_ID) VALUES (2, 0, 'VENOM', 'akcio-horror', '2018-09-02', 1);
INSERT INTO MOVIE (ID, VERSION, TITLE, GENRE, PUBLICATION_DATE, DIRECTOR_ID) VALUES (3, 0, 'A HIHETETLEN CSALAD 2', 'animacios', '2018-09-03', (select ID FROM DIRECTOR where DIRECTOR_NAME = 'Brad Bird') );
INSERT INTO MOVIE (ID, VERSION, TITLE, GENRE, PUBLICATION_DATE, DIRECTOR_ID) VALUES (4, 0, 'AZ APACA', 'horror', '2018-09-04', 1);

INSERT INTO MOVIE_DIRECTOR (MOVIES_ID, DIRECTORS_ID) VALUES (1, 2);
INSERT INTO MOVIE_DIRECTOR (MOVIES_ID, DIRECTORS_ID) VALUES (2, 2);
INSERT INTO MOVIE_DIRECTOR (MOVIES_ID, DIRECTORS_ID) VALUES (3, 2);
INSERT INTO MOVIE_DIRECTOR (MOVIES_ID, DIRECTORS_ID) VALUES (4, 1);
